### ISSUE TITLE
some questions about the usage of Optane DC

### ISSUE THREAD

**Issue by XiaominZou** [utsaslab/RECIPE#3]
Excuse me, I have read your paper, and I have some questions about your test:
1. Did you configure App Direct mode with interleaved modules?
2. How did you measure high throughput(77.64Mops/s for CCEH) in Optane DC?
3. Did you test the scalability of your P-CLHT? The scalability of other common data structure I tested is not good, I wonder it is limited by the Optane DC.
I hope that you can take the time to answer for me during your busy schedule, thank you！.

**Comment by SeKwonLee** [comment]
Hi,

1. We used App direct mode.
2. The throughput can be different depending on the machine you use. Our machine for running real PM experiments has 32MB L3 cache. On this machine, CCEH shows low cache miss rate since the size of its global dictionary was fit into 32MB L3 cache.
3. CLHT's scalability has lots of variance depending on whether rehashing happens or not while running workloads. In our experiments, except for YCSB load workload, we measured the performance without rehashing.

Thanks
